services:
  postgres:
    image: postgres:17
    platform: linux/arm64
    container_name: erp_db
    environment:
      POSTGRES_DB: erp_db
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_password
    ports:
      - "5432:5432"
    volumes:
      - erp_postgres_data:/var/lib/postgresql/data
volumes:
  erp_postgres_data: